local M = {}

local function style(enabled, name)
  if enabled then
    return name == "italic"
  end
  return nil
end

local function groups(c, opts)
  local bg = opts.transparent and c.none or c.bg
  local bg_alt = opts.transparent and c.none or c.bg_alt
  local bg_raised = opts.transparent and c.none or c.bg_raised
  local comments = style(opts.italics.comments, "italic")
  local keywords = style(opts.italics.keywords, "italic")
  local functions = style(opts.italics.functions, "italic")
  local strings = style(opts.italics.strings, "italic")
  local variables = style(opts.italics.variables, "italic")

  return {
    Normal = { fg = c.fg, bg = bg },
    NormalNC = { fg = c.fg, bg = bg },
    NormalFloat = { fg = c.fg, bg = bg_alt },
    FloatBorder = { fg = c.border, bg = bg_alt },
    FloatTitle = { fg = c.orange, bg = bg_alt, bold = true },
    ColorColumn = { bg = bg_alt },
    Conceal = { fg = c.comment },
    Cursor = { fg = c.bg, bg = c.orange },
    CursorColumn = { bg = bg_alt },
    CursorLine = { bg = bg_alt },
    CursorLineNr = { fg = c.orange, bg = bg_alt, bold = true },
    Directory = { fg = c.orange },
    EndOfBuffer = { fg = c.bg_raised },
    ErrorMsg = { fg = c.red },
    FoldColumn = { fg = c.comment, bg = bg },
    Folded = { fg = c.fg_muted, bg = bg_alt },
    IncSearch = { fg = c.bg, bg = c.orange },
    LineNr = { fg = c.comment },
    MatchParen = { fg = c.orange, bg = c.bg_raised, bold = true },
    ModeMsg = { fg = c.fg_muted },
    MoreMsg = { fg = c.mint },
    NonText = { fg = c.comment },
    Pmenu = { fg = c.fg, bg = bg_alt },
    PmenuSbar = { bg = c.bg_raised },
    PmenuSel = { fg = c.orange, bg = bg_raised },
    PmenuThumb = { bg = c.border },
    Question = { fg = c.mint },
    QuickFixLine = { bg = bg_alt, bold = true },
    Search = { fg = c.fg, bg = c.orange_soft },
    SignColumn = { fg = c.comment, bg = bg },
    SpecialKey = { fg = c.comment },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.orange, undercurl = true },
    SpellLocal = { sp = c.mint, undercurl = true },
    SpellRare = { sp = c.magenta, undercurl = true },
    StatusLine = { fg = c.fg_muted, bg = bg_alt },
    StatusLineNC = { fg = c.comment, bg = bg_alt },
    Substitute = { fg = c.bg, bg = c.mint },
    TabLine = { fg = c.fg_muted, bg = bg_alt },
    TabLineFill = { fg = c.comment, bg = bg_alt },
    TabLineSel = { fg = c.orange, bg = bg },
    Title = { fg = c.orange, bold = true },
    VertSplit = { fg = c.border },
    Visual = { bg = c.orange_soft },
    WarningMsg = { fg = c.orange },
    Whitespace = { fg = c.border },
    WildMenu = { fg = c.orange, bg = bg_raised },
    WinSeparator = { fg = c.border },

    Comment = { fg = c.comment, italic = comments },
    Constant = { fg = c.orange },
    String = { fg = c.mint, italic = strings },
    Character = { fg = c.mint },
    Number = { fg = c.orange },
    Boolean = { fg = c.orange },
    Float = { fg = c.orange },
    Identifier = { fg = c.fg, italic = variables },
    Function = { fg = c.orange, italic = functions },
    Statement = { fg = c.fg_muted, italic = keywords },
    Conditional = { fg = c.fg_muted, italic = keywords },
    Repeat = { fg = c.fg_muted, italic = keywords },
    Label = { fg = c.fg_muted },
    Operator = { fg = c.fg_muted },
    Keyword = { fg = c.fg_muted, italic = keywords },
    Exception = { fg = c.fg_muted },
    PreProc = { fg = c.fg_muted },
    Include = { fg = c.fg_muted },
    Define = { fg = c.fg_muted },
    Macro = { fg = c.orange },
    PreCondit = { fg = c.fg_muted },
    Type = { fg = c.orange },
    StorageClass = { fg = c.fg_muted },
    Structure = { fg = c.orange },
    Typedef = { fg = c.orange },
    Special = { fg = c.orange },
    SpecialChar = { fg = c.orange },
    Tag = { fg = c.orange },
    Delimiter = { fg = c.fg_muted },
    SpecialComment = { fg = c.comment, italic = comments },
    Debug = { fg = c.red },
    Underlined = { fg = c.orange, underline = true },
    Ignore = { fg = c.comment },
    Error = { fg = c.red },
    Todo = { fg = c.orange, bg = c.orange_soft, bold = true },

    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.orange },
    DiagnosticInfo = { fg = c.mint },
    DiagnosticHint = { fg = c.fg_muted },
    DiagnosticOk = { fg = c.mint },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.orange, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.mint, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.fg_muted, undercurl = true },
    DiagnosticVirtualTextError = { fg = c.red, bg = c.red_soft },
    DiagnosticVirtualTextWarn = { fg = c.orange, bg = c.orange_soft },
    DiagnosticVirtualTextInfo = { fg = c.mint, bg = c.mint_soft },
    DiagnosticVirtualTextHint = { fg = c.fg_muted, bg = bg_alt },
    LspReferenceText = { bg = bg_raised },
    LspReferenceRead = { bg = bg_raised },
    LspReferenceWrite = { bg = bg_raised },

    DiffAdd = { fg = c.mint, bg = c.mint_soft },
    DiffChange = { fg = c.fg_muted, bg = bg_alt },
    DiffDelete = { fg = c.red, bg = c.red_soft },
    DiffText = { fg = c.orange, bg = c.orange_soft },
    Added = { fg = c.mint },
    Changed = { fg = c.fg_muted },
    Removed = { fg = c.red },

    GitSignsAdd = { fg = c.mint, bg = bg },
    GitSignsChange = { fg = c.orange, bg = bg },
    GitSignsDelete = { fg = c.red, bg = bg },

    ["@variable"] = { fg = c.fg, italic = variables },
    ["@variable.builtin"] = { fg = c.fg_muted },
    ["@variable.parameter"] = { fg = c.fg, italic = variables },
    ["@variable.member"] = { fg = c.fg },
    ["@constant"] = { fg = c.orange },
    ["@constant.builtin"] = { fg = c.orange },
    ["@constant.macro"] = { fg = c.orange },
    ["@module"] = { fg = c.fg },
    ["@label"] = { fg = c.fg_muted },
    ["@string"] = { fg = c.mint, italic = strings },
    ["@string.documentation"] = { fg = c.mint, italic = strings },
    ["@string.regexp"] = { fg = c.fg_muted },
    ["@string.escape"] = { fg = c.orange },
    ["@character"] = { fg = c.mint },
    ["@number"] = { fg = c.orange },
    ["@boolean"] = { fg = c.orange },
    ["@float"] = { fg = c.orange },
    ["@function"] = { fg = c.orange, italic = functions },
    ["@function.builtin"] = { fg = c.orange, italic = functions },
    ["@function.call"] = { fg = c.orange, italic = functions },
    ["@function.macro"] = { fg = c.orange, italic = functions },
    ["@method"] = { fg = c.orange, italic = functions },
    ["@method.call"] = { fg = c.orange, italic = functions },
    ["@constructor"] = { fg = c.orange },
    ["@keyword"] = { fg = c.fg_muted, italic = keywords },
    ["@keyword.function"] = { fg = c.fg_muted, italic = keywords },
    ["@keyword.operator"] = { fg = c.fg_muted },
    ["@keyword.return"] = { fg = c.fg_muted, italic = keywords },
    ["@conditional"] = { fg = c.fg_muted, italic = keywords },
    ["@repeat"] = { fg = c.fg_muted, italic = keywords },
    ["@operator"] = { fg = c.fg_muted },
    ["@type"] = { fg = c.orange },
    ["@type.builtin"] = { fg = c.orange },
    ["@property"] = { fg = c.fg },
    ["@field"] = { fg = c.fg },
    ["@punctuation.delimiter"] = { fg = c.fg_muted },
    ["@punctuation.bracket"] = { fg = c.fg_muted },
    ["@punctuation.special"] = { fg = c.fg_muted },
    ["@comment"] = { fg = c.comment, italic = comments },
    ["@comment.documentation"] = { fg = c.comment, italic = comments },
    ["@error"] = { fg = c.red },
    ["@tag"] = { fg = c.orange },
    ["@tag.attribute"] = { fg = c.orange },
    ["@tag.delimiter"] = { fg = c.fg_muted },
    ["@markup.heading"] = { fg = c.orange, bold = true },
    ["@markup.strong"] = { fg = c.fg, bold = true },
    ["@markup.italic"] = { fg = c.fg, italic = true },
    ["@markup.link"] = { fg = c.orange, underline = true },
    ["@markup.link.url"] = { fg = c.fg_muted, underline = true },
    ["@markup.raw"] = { fg = c.fg_muted },
    ["@diff.plus"] = { fg = c.mint },
    ["@diff.minus"] = { fg = c.red },
    ["@diff.delta"] = { fg = c.orange },

    TelescopeNormal = { fg = c.fg, bg = bg_alt },
    TelescopeBorder = { fg = c.border, bg = bg_alt },
    TelescopePromptNormal = { fg = c.fg, bg = bg_raised },
    TelescopePromptBorder = { fg = c.border, bg = bg_raised },
    TelescopePromptTitle = { fg = c.bg, bg = c.orange },
    TelescopePreviewTitle = { fg = c.bg, bg = c.mint },
    TelescopeResultsTitle = { fg = c.bg, bg = c.fg_muted },
    TelescopeSelection = { fg = c.orange, bg = bg_raised },
    TelescopeMatching = { fg = c.orange, bold = true },

    NvimTreeNormal = { fg = c.fg, bg = bg_alt },
    NvimTreeFolderName = { fg = c.orange },
    NvimTreeOpenedFolderName = { fg = c.orange, bold = true },
    NvimTreeRootFolder = { fg = c.fg_muted, bold = true },
    NvimTreeGitDirty = { fg = c.orange },
    NvimTreeGitNew = { fg = c.mint },
    NvimTreeGitDeleted = { fg = c.red },
    NeoTreeNormal = { fg = c.fg, bg = bg_alt },
    NeoTreeDirectoryName = { fg = c.orange },
    NeoTreeGitAdded = { fg = c.mint },
    NeoTreeGitModified = { fg = c.orange },
    NeoTreeGitDeleted = { fg = c.red },

    CmpItemAbbr = { fg = c.fg },
    CmpItemAbbrDeprecated = { fg = c.comment, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.orange, bold = true },
    CmpItemKind = { fg = c.fg_muted },
    CmpItemMenu = { fg = c.comment },

    WhichKey = { fg = c.orange },
    WhichKeyGroup = { fg = c.mint },
    WhichKeyDesc = { fg = c.fg },
    WhichKeySeparator = { fg = c.comment },
    WhichKeyValue = { fg = c.comment },

    LazyNormal = { fg = c.fg, bg = bg_alt },
    LazyButton = { fg = c.fg_muted, bg = bg_raised },
    LazyButtonActive = { fg = c.orange, bg = bg_raised, bold = true },
    LazyH1 = { fg = c.bg, bg = c.orange, bold = true },
    LazyH2 = { fg = c.orange, bold = true },

    BufferLineFill = { bg = bg_alt },
    BufferLineBackground = { fg = c.fg_muted, bg = bg_alt },
    BufferLineBufferSelected = { fg = c.fg, bg = bg, bold = true },
    BufferLineIndicatorSelected = { fg = c.orange, bg = bg },
    BufferLineModified = { fg = c.orange, bg = bg_alt },
    BufferLineModifiedSelected = { fg = c.orange, bg = bg },
  }
end

function M.get(c, opts)
  return groups(c, opts)
end

function M.lualine(c, opts)
  local bg = opts.transparent and c.bg_alt or c.bg

  return {
    normal = {
      a = { fg = c.bg, bg = c.orange, gui = "bold" },
      b = { fg = c.fg_muted, bg = c.bg_alt },
      c = { fg = c.fg, bg = bg },
    },
    insert = {
      a = { fg = c.bg, bg = c.mint, gui = "bold" },
    },
    visual = {
      a = { fg = c.bg, bg = c.fg_muted, gui = "bold" },
    },
    replace = {
      a = { fg = c.bg, bg = c.red, gui = "bold" },
    },
    command = {
      a = { fg = c.bg, bg = c.orange, gui = "bold" },
    },
    inactive = {
      a = { fg = c.comment, bg = c.bg_alt },
      b = { fg = c.comment, bg = c.bg_alt },
      c = { fg = c.comment, bg = bg },
    },
  }
end

return M
